### ISSUE TITLE
Theoretical unsafe if condition

### ISSUE THREAD

**Issue by mfbx9da4** [bloomberg/record-tuple-polyfill#106]
https://github.com/bloomberg/record-tuple-polyfill/blob/5f9cae34f0d331c4836efbc9cd618836c03e75f5/packages/record-tuple-polyfill/src/interngraph.js#L55

Theoretically couldn't the value be garbage collected between calls to `ref.deref()`? So therefore `InternGraph.deref()` could return `undefined`?

```typescript
if (ref && ref.deref()) {
  return ref.deref();
}
```

Suggestion:

```typescript
const existingValue = ref?.deref()
if (existingValue) {
  return existingValue;
}
```

**Comment by mhofman** [comment]
`foo.deref()` is guaranteed to return the same value when called in the same synchronous execution. Forcing a GC between the 2 calls here will never return undefined for the second call by spec
