### ISSUE TITLE
JSON.parseImmutable not implemented

### ISSUE THREAD

**Issue by rricard** [bloomberg/record-tuple-polyfill#14]
**Describe the bug**

JSON.parseImmutable is missing

**To Reproduce**

```js

const user = JSON.parseImmutable('{ "name": "danny", "admin": false, "score": 42 }');
```

```
    "JSON.parseImmutable is not a function"

    TypeError {}
```

**Expected behavior**

Json gets parsed into a record

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10
 - Firefox 78

**Additional context**

**Comment by nicolo-ribaudo** [comment]
This has been fixed
