### ISSUE TITLE
WeakMap.set(Record) does not trigger a TypeError as stated in [proposal](https://github.com/tc39/proposal-record-tuple#weakmap-and-weakset)

### ISSUE THREAD

**Issue by Vinsurs** [bloomberg/record-tuple-polyfill#76]
**Describe the bug**
WeakMap.set(Record) does not throw a TypeError as stated in proposal.

**To Reproduce**
There is my code:
babel.config.js
```js
module.exports = {
    presets: ["@babel/preset-env"],
    plugins: [
        ["@babel/plugin-proposal-record-and-tuple", {
            importPolyfill: true,
            // "hash" | "bar"
            syntaxType: "hash"  
        }]
    ]
}
```
index.js
```js
const imutableRecord_1 = #{
    name: "vinsurs",
    age: 18
}
const imutableTuple_1 = #[1, 2, 4]

const weakMap = new WeakMap()
weakMap.set(imutableRecord_1, "imutableRecord")
weakMap.set(imutableTuple_1, "imutableTuple")
// TypeError does not throw and can get results normally.
console.log("weakMap", weakMap.get(imutableRecord_1), weakMap.get(imutableTuple_1))
```
**Current behavior**
The console can log result normally
**Expected behavior**
The console should throw a TypeError because WeakMap cannot accept a [primitive value](https://github.com/tc39/proposal-record-tuple#compound-primitive-types) as it's key, or as mentioned in [Record-and-Tuple Proposal](https://github.com/tc39/proposal-record-tuple#weakmap-and-weakset)..

**Environment (please complete the following information):**
 + System:
    - OS: Windows 10 10.0.19042
+ Binaries:
    - Node: 16.12.0
    - Yarn: 1.22.17
    -  npm: 8.3.0
+ npmPackages:
    -  @babel/cli: ^7.17.6 => 7.17.6
    - @babel/core: ^7.17.8 => 7.17.8
   - @babel/plugin-proposal-record-and-tuple: ^7.16.7 => 7.16.7
   - @babel/preset-env: ^7.16.11 => 7.16.11

**Comment by rickbutton** [comment]
Great catch. This makes sense, since records are polyfilled as interned objects. The easiest solution for this is probably to just patch `WeakMap.prototype.set`.
